on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Create production build
        run: npm run build
        env:
          CI: ""
          LEAFLET_API_KEY: "${{ secrets.LEAFLET_API_KEY }}"
          REACT_APP_BASEURL: "${{ secrets.REACT_APP_BASEURL }}"
          REACT_APP_SOCKET_BASEURL: "${{ secrets.REACT_APP_SOCKET_BASEURL }}"
          REACT_APP_LOCATION_IQ_API_KEY: "${{ secrets.REACT_APP_LOCATION_IQ_API_KEY }}"
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: sportflix-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Downloading Artifact
        uses: actions/download-artifact@v3
        with:
          name: sportflix-build
          path: sportflix-build

      - name: Show files
        run: ls -R

      - name: Push to s3 bucket
        uses: reggionick/s3-deploy@v4
        with:
          folder: sportflix-build
          bucket: "${{ secrets.AWS_BUCKET }}"
          bucket-region: "${{ secrets.AWS_REGION }}"
          files-to-include: ".*/*,*/*,**"
