on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Create production build
        run: npm run build
        env:
          CI: ""
          LEAFLET_API_KEY: "${{ secrets.LEAFLET_API_KEY }}"
          REACT_APP_BASEURL: "${{ secrets.REACT_APP_BASEURL }}"
          REACT_APP_SOCKET_BASEURL: "${{ secrets.REACT_APP_SOCKET_BASEURL }}"
          REACT_APP_LOCATION_IQ_API_KEY: "${{ secrets.REACT_APP_LOCATION_IQ_API_KEY }}"

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: sportflix-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Downloading Artifact
        uses: actions/download-artifact@v3
        with:
          name: sportflix-build
          path: sportflix-build

      - name: Show files
        run: ls -R

      - name: Upload to S3 bucket
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: sportflix-build
