on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Create production build
        run: npm run build
        env:
          CI: ""
          LEAFLET_API_KEY:
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: sportflix-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the shared artifact
      - name: Downloading Artifact
        uses: actions/download-artifact@v3
        with:
          name: sportflix-build
      - name: Display the downloaded files
        run: ls -R
